/**
 * modules/manuscripts/clsi/core/adapters/engines/bib-backend.detector.ts
 * Auto-detects whether the document requires modern Biber or traditional BibTeX,
 * and generates project-level .latexmkrc configuration matching Overleaf CLSI.
 */

import * as fs from 'fs/promises';
import * as path from 'path';

export type BibBackend = 'biber' | 'bibtex';

export interface LatexmkrcOptions {
  engine: 'pdflatex' | 'xelatex' | 'lualatex' | 'tectonic';
  bibBackend: BibBackend;
  shellEscape?: boolean;
}

export class BibBackendDetector {
  /**
   * Analyzes TeX source and existing auxiliary files in scratchDir
   * to determine whether Biber or BibTeX should be used.
   */
  public static async detect(
    source: string,
    scratchDir?: string,
    magicBibHint?: 'biber' | 'bibtex'
  ): Promise<BibBackend> {
    // 1. Honor explicit magic comment (% !BIB program = biber/bibtex)
    if (magicBibHint) {
      return magicBibHint;
    }

    // 2. Check disk for .bcf (BibLaTeX Control File) if scratchDir is provided
    if (scratchDir) {
      try {
        const entries = await fs.readdir(scratchDir);
        if (entries.some((file) => file.endsWith('.bcf'))) {
          return 'biber';
        }
      } catch {
        // Directory may not exist yet
      }
    }

    if (!source) {
      return 'bibtex';
    }

    // 3. Inspect source for biblatex package declaration
    const biblatexMatch = source.match(
      /\\usepackage(?:\[([^\]]*)\])?\{biblatex\}/i
    );

    if (biblatexMatch) {
      const options = biblatexMatch[1] || '';
      // If backend=bibtex or backend=bibtex8 is explicitly requested
      if (/backend\s*=\s*bibtex[0-9]*/i.test(options)) {
        return 'bibtex';
      }
      // Otherwise biblatex defaults to biber
      return 'biber';
    }

    // 4. Traditional natbib or \bibliography{} uses bibtex
    if (
      /\\bibliography\{/i.test(source) ||
      /\\bibliographystyle\{/i.test(source) ||
      /\\usepackage(?:\[[^\]]*\])?\{natbib\}/i.test(source)
    ) {
      return 'bibtex';
    }

    // Default to bibtex for standard documents
    return 'bibtex';
  }

  /**
   * Generates a project-level .latexmkrc string configured with
   * optimal convergence, bibliography tools, and optional shell-escape.
   */
  public static generateLatexmkrc(options: LatexmkrcOptions): string {
    const lines: string[] = [
      '# Auto-generated by Flux CLSI (Overleaf Parity)',
      `$biber = 'biber %O %S';`,
      `$bibtex = 'bibtex %O %B';`,
    ];

    const shellEscapeFlag = options.shellEscape ? ' -shell-escape' : '';

    if (options.engine === 'xelatex') {
      lines.push(`$pdf_mode = 5;`);
      lines.push(`$xelatex = 'xelatex %O${shellEscapeFlag} %S';`);
    } else if (options.engine === 'lualatex') {
      lines.push(`$pdf_mode = 4;`);
      lines.push(`$lualatex = 'lualatex %O${shellEscapeFlag} %S';`);
    } else {
      lines.push(`$pdf_mode = 1;`);
      lines.push(`$pdflatex = 'pdflatex %O${shellEscapeFlag} %S';`);
    }

    // Convergence tuning: max 5 passes to resolve complex cross-references
    lines.push('$max_repeat = 5;');

    return lines.join('\n') + '\n';
  }

  /**
   * Writes the .latexmkrc file to the project's scratch directory.
   */
  public static async writeLatexmkrc(
    scratchDir: string,
    options: LatexmkrcOptions
  ): Promise<string> {
    const filePath = path.join(scratchDir, '.latexmkrc');
    const content = this.generateLatexmkrc(options);
    await fs.writeFile(filePath, content, 'utf8');
    return filePath;
  }
}
