/**
 * document-updater/core/domain/value-objects/update-op.vo.ts
 * Value Object encapsulating an in-flight document update delta or batch.
 */

export interface UpdateOpProps {
  /** Timestamp when operation was generated by user client */
  timestamp?: number;
  /** User identifier who made the change */
  userId?: string;
  /** Full lines array replacement (most common high-efficiency mode from Overleaf/ShareJS) */
  lines?: string[];
  /** Incremental line splice (start index, delete count, new lines) */
  splice?: {
    startLine: number;
    deleteCount: number;
    newLines: string[];
  };
  /** Target revision expected by client */
  clientRev?: number;
}

export class UpdateOpVo {
  public readonly timestamp: number;
  public readonly userId?: string;
  public readonly lines?: string[];
  public readonly splice?: {
    startLine: number;
    deleteCount: number;
    newLines: string[];
  };
  public readonly clientRev?: number;

  private constructor(props: UpdateOpProps) {
    this.timestamp = props.timestamp ?? Date.now();
    this.userId = props.userId;
    this.lines = props.lines;
    this.splice = props.splice;
    this.clientRev = props.clientRev;
  }

  public static fromLines(lines: string[], userId?: string, clientRev?: number): UpdateOpVo {
    return new UpdateOpVo({
      lines,
      userId,
      clientRev,
      timestamp: Date.now(),
    });
  }

  public static fromSplice(
    startLine: number,
    deleteCount: number,
    newLines: string[],
    userId?: string,
    clientRev?: number,
  ): UpdateOpVo {
    return new UpdateOpVo({
      splice: { startLine, deleteCount, newLines },
      userId,
      clientRev,
      timestamp: Date.now(),
    });
  }

  /**
   * Applies this operation to an existing lines array and returns the resulting new lines array.
   */
  public applyTo(baseLines: string[]): string[] {
    if (this.lines) {
      return [...this.lines];
    }
    if (this.splice) {
      const next = [...baseLines];
      next.splice(this.splice.startLine, this.splice.deleteCount, ...this.splice.newLines);
      return next;
    }
    return baseLines;
  }
}
