import { Permission } from '../enums/permissions.enum';
import { WorkspaceRole } from '../enums/workspace-role.enum';
import { ProjectRole } from '../enums/project-role.enum';

/**
 * Workspace-level role permissions mapping
 */
export const WORKSPACE_ROLE_PERMISSIONS: Record<WorkspaceRole, Permission[]> = {
  [WorkspaceRole.OWNER]: Object.values(Permission),

  [WorkspaceRole.ADMIN]: [
    Permission.WORKSPACE_READ,
    Permission.WORKSPACE_UPDATE,
    Permission.WORKSPACE_INVITE,
    Permission.WORKSPACE_REMOVE_MEMBER,
    Permission.WORKSPACE_UPDATE_ROLE,
    Permission.PROJECT_READ,
    Permission.PROJECT_CREATE,
    Permission.PROJECT_UPDATE,
    Permission.PROJECT_DELETE,
    Permission.PROJECT_MANAGE_MEMBERS,
    Permission.TASK_READ,
    Permission.TASK_CREATE,
    Permission.TASK_UPDATE,
    Permission.TASK_DELETE,
    Permission.CYCLE_READ,
    Permission.CYCLE_MANAGE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_EDIT,
    Permission.DOCUMENT_DELETE,
    Permission.DOCUMENT_COMPILE,
    Permission.COMMENT_READ,
    Permission.COMMENT_CREATE,
    Permission.COMMENT_DELETE,
    Permission.LABEL_READ,
    Permission.LABEL_MANAGE,
    Permission.STICKY_READ,
    Permission.STICKY_CREATE,
    Permission.STICKY_UPDATE,
    Permission.STICKY_DELETE,
    Permission.FILE_READ,
    Permission.FILE_UPLOAD,
    Permission.FILE_DELETE,
    Permission.PAPER_READ,
    Permission.PAPER_INGEST,
    Permission.PAPER_DELETE,
    Permission.ANALYTICS_READ,
  ],

  [WorkspaceRole.MEMBER]: [
    Permission.WORKSPACE_READ,
    Permission.PROJECT_READ,
    Permission.PROJECT_CREATE,
    Permission.TASK_READ,
    Permission.TASK_CREATE,
    Permission.TASK_UPDATE,
    Permission.CYCLE_READ,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_EDIT,
    Permission.DOCUMENT_COMPILE,
    Permission.COMMENT_READ,
    Permission.COMMENT_CREATE,
    Permission.LABEL_READ,
    Permission.STICKY_READ,
    Permission.STICKY_CREATE,
    Permission.STICKY_UPDATE,
    Permission.FILE_READ,
    Permission.FILE_UPLOAD,
    Permission.PAPER_READ,
    Permission.PAPER_INGEST,
    Permission.ANALYTICS_READ,
  ],

  [WorkspaceRole.VIEWER]: [
    Permission.WORKSPACE_READ,
    Permission.PROJECT_READ,
    Permission.TASK_READ,
    Permission.CYCLE_READ,
    Permission.DOCUMENT_READ,
    Permission.COMMENT_READ,
    Permission.LABEL_READ,
    Permission.STICKY_READ,
    Permission.FILE_READ,
    Permission.PAPER_READ,
    Permission.ANALYTICS_READ,
  ],
};

/**
 * Project-level role permissions mapping
 */
export const PROJECT_ROLE_PERMISSIONS: Record<ProjectRole, Permission[]> = {
  [ProjectRole.ADMIN]: [
    Permission.PROJECT_READ,
    Permission.PROJECT_UPDATE,
    Permission.PROJECT_DELETE,
    Permission.PROJECT_MANAGE_MEMBERS,
    Permission.TASK_READ,
    Permission.TASK_CREATE,
    Permission.TASK_UPDATE,
    Permission.TASK_DELETE,
    Permission.CYCLE_READ,
    Permission.CYCLE_MANAGE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_EDIT,
    Permission.DOCUMENT_DELETE,
    Permission.DOCUMENT_COMPILE,
    Permission.COMMENT_READ,
    Permission.COMMENT_CREATE,
    Permission.COMMENT_DELETE,
    Permission.LABEL_READ,
    Permission.LABEL_MANAGE,
    Permission.STICKY_READ,
    Permission.STICKY_CREATE,
    Permission.STICKY_UPDATE,
    Permission.STICKY_DELETE,
    Permission.FILE_READ,
    Permission.FILE_UPLOAD,
    Permission.FILE_DELETE,
  ],

  [ProjectRole.CONTRIBUTOR]: [
    Permission.PROJECT_READ,
    Permission.TASK_READ,
    Permission.TASK_CREATE,
    Permission.TASK_UPDATE,
    Permission.CYCLE_READ,
    Permission.CYCLE_MANAGE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_EDIT,
    Permission.DOCUMENT_COMPILE,
    Permission.COMMENT_READ,
    Permission.COMMENT_CREATE,
    Permission.LABEL_READ,
    Permission.STICKY_READ,
    Permission.STICKY_CREATE,
    Permission.STICKY_UPDATE,
    Permission.FILE_READ,
    Permission.FILE_UPLOAD,
  ],

  [ProjectRole.COMMENTER]: [
    Permission.PROJECT_READ,
    Permission.TASK_READ,
    Permission.CYCLE_READ,
    Permission.DOCUMENT_READ,
    Permission.COMMENT_READ,
    Permission.COMMENT_CREATE,
    Permission.LABEL_READ,
    Permission.STICKY_READ,
    Permission.STICKY_CREATE,
    Permission.FILE_READ,
  ],

  [ProjectRole.VIEWER]: [
    Permission.PROJECT_READ,
    Permission.TASK_READ,
    Permission.CYCLE_READ,
    Permission.DOCUMENT_READ,
    Permission.COMMENT_READ,
    Permission.LABEL_READ,
    Permission.STICKY_READ,
    Permission.FILE_READ,
  ],
};
