import {
  IsEnum,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
} from 'class-validator';
import { ApiPropertyOptional } from '@nestjs/swagger';
import { CommentStatus } from '@prisma/client';

export class CreateCommentDto {
  @IsString()
  @IsNotEmpty({ message: 'Comment content is required' })
  content!: string;

  @IsEnum(CommentStatus)
  @IsOptional()
  status?: CommentStatus;

  @IsNumber()
  @IsOptional()
  line?: number;

  @IsNumber()
  @IsOptional()
  lineEnd?: number;

  @IsString()
  @IsOptional()
  projectId?: string;

  @IsString()
  @IsOptional()
  pageId?: string;

  /**
   * JSON-encoded Y.RelativePosition for the start of the highlighted range.
   * Generated by the frontend editor: JSON.stringify(Y.relativePositionToJSON(relPos))
   * Stays accurate after concurrent edits — no manual range tracking needed.
   */
  @IsString()
  @IsOptional()
  @ApiPropertyOptional({
    description: 'JSON-encoded Yjs RelativePosition for comment anchor start',
  })
  yjsAnchorStart?: string;

  /**
   * JSON-encoded Y.RelativePosition for the end of the highlighted range.
   */
  @IsString()
  @IsOptional()
  @ApiPropertyOptional({
    description: 'JSON-encoded Yjs RelativePosition for comment anchor end',
  })
  yjsAnchorEnd?: string;

  /**
   * Snapshot of the highlighted text at comment creation time (shown for context when anchor drifts).
   */
  @IsString()
  @IsOptional()
  @ApiPropertyOptional({
    description: 'Text selected when comment was created',
  })
  selectedText?: string;
}

export class UpdateCommentDto {
  @IsString()
  @IsOptional()
  content?: string;

  @IsEnum(CommentStatus)
  @IsOptional()
  status?: CommentStatus;

  @IsString()
  @IsOptional()
  projectId?: string;
}

export class AddReplyDto {
  @IsString()
  @IsNotEmpty({ message: 'Reply content is required' })
  content!: string;

  @IsString()
  @IsOptional()
  projectId?: string;
}
