/**
 * modules/manuscripts/clsi/clsi.controller.ts
 * NestJS Controller exposing CLSI compilation, SyncTeX, and artifact endpoints.
 */

import {
  Controller,
  Post,
  Get,
  Body,
  Param,
  Res,
  UseGuards,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { ApiTags, ApiBearerAuth, ApiOperation } from '@nestjs/swagger';
import { JwtAuthGuard } from '@/modules/identity/auth';
import { CurrentUser } from '@/modules/identity/auth';
import { ProjectRoleGuard, ProjectRoles } from '@/modules/project/access';
import { ClsiService } from './clsi.service';
import {
  CompileManuscriptDto,
  ClsiWordCountDto,
} from './dto/clsi.dto';
import {
  ForwardSyncDto,
  ReverseSyncDto,
} from './dto/synctex.dto';

@ApiTags('Manuscripts - CLSI')
@ApiBearerAuth('JWT-auth')
@Controller('api')
@UseGuards(JwtAuthGuard)
export class ClsiController {
  constructor(private readonly clsiService: ClsiService) {}

  @Post([
    'v1/manuscripts/compile',
    'manuscripts/compile',
    'clsi/compile',
    'compiler/compile',
    'latex/compile',
  ])
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Compile LaTeX manuscript source to PDF via Overleaf-parity CLSI',
  })
  async compile(
    @Body() dto: CompileManuscriptDto,
    @CurrentUser('id') userId: string
  ) {
    return this.clsiService.compile(dto, userId);
  }

  @Post([
    'v1/manuscripts/word-count',
    'manuscripts/word-count',
    'clsi/word-count',
    'compiler/word-count',
    'latex/word-count',
  ])
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Calculate academic word count and metrics (texcount parity)',
  })
  async wordCount(@Body() dto: ClsiWordCountDto) {
    return this.clsiService.getWordCount(dto);
  }

  @Post([
    'v1/manuscripts/synctex/forward',
    'synctex/forward',
    'manuscripts/synctex/forward',
    'clsi/synctex/forward',
    'latex/synctex/forward',
    'projects/:projectId/clsi/synctex/forward',
  ])
  @UseGuards(ProjectRoleGuard)
  @ProjectRoles('owner', 'coordinator', 'contributor', 'reviewer')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Forward SyncTeX: map LaTeX source line/column to PDF coordinates',
  })
  async forwardSync(@Body() dto: ForwardSyncDto) {
    return this.clsiService.forwardSync(dto);
  }

  @Post([
    'v1/manuscripts/synctex/reverse',
    'synctex/reverse',
    'manuscripts/synctex/reverse',
    'clsi/synctex/reverse',
    'latex/synctex/reverse',
    'projects/:projectId/clsi/synctex/reverse',
  ])
  @UseGuards(ProjectRoleGuard)
  @ProjectRoles('owner', 'coordinator', 'contributor', 'reviewer')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary:
      'Reverse SyncTeX: map clicked PDF page coordinates to LaTeX source line/column',
  })
  async reverseSync(@Body() dto: ReverseSyncDto) {
    return this.clsiService.reverseSync(dto);
  }

  @Get([
    'v1/manuscripts/projects/:projectId/artifacts',
    ':projectId/clsi/artifacts',
    ':projectId/compiler/artifacts',
  ])
  @UseGuards(ProjectRoleGuard)
  @ProjectRoles('owner', 'coordinator', 'contributor', 'reviewer')
  @ApiOperation({
    summary: 'List auxiliary files generated by CLSI compilation',
  })
  async listAuxFiles(@Param('projectId') projectId: string) {
    return this.clsiService.listAuxFiles(projectId);
  }

  @Get([
    'v1/manuscripts/projects/:projectId/artifacts/:filename',
    ':projectId/clsi/artifacts/:filename',
    ':projectId/compiler/artifacts/:filename',
  ])
  @UseGuards(ProjectRoleGuard)
  @ProjectRoles('owner', 'coordinator', 'contributor', 'reviewer')
  @ApiOperation({ summary: 'Download a specific auxiliary file' })
  async downloadAuxFile(
    @Param('projectId') projectId: string,
    @Param('filename') filename: string,
    @Res() res: any
  ) {
    return this.clsiService.downloadAuxFile(projectId, filename, res);
  }

  @Get(':projectId/clsi/artifacts-zip')
  @UseGuards(ProjectRoleGuard)
  @ProjectRoles('owner', 'coordinator', 'contributor', 'reviewer')
  @ApiOperation({ summary: 'Download all project output artifacts packaged as a ZIP archive' })
  async downloadAllArtifactsZip(
    @Param('projectId') projectId: string,
    @Res() res: any
  ) {
    return this.clsiService.downloadAllArtifactsZip(projectId, res);
  }

  @Get(['clsi/status', 'manuscripts/clsi/status'])
  @ApiOperation({ summary: 'Check health status and probe TeX Live compiler binaries' })
  async getStatus() {
    return this.clsiService.getHealthReport();
  }

  @Get(['clsi/metrics', 'manuscripts/clsi/metrics'])
  @ApiOperation({ summary: 'Prometheus metrics endpoint for CLSI compilation performance' })
  async getMetrics(@Res() res: any) {
    const metricsText = this.clsiService.getPrometheusMetrics();
    res.setHeader('Content-Type', 'text/plain; version=0.0.4');
    res.send(metricsText);
  }

  @Get(['clsi/metrics/summary', 'manuscripts/clsi/metrics/summary'])
  @ApiOperation({ summary: 'JSON metrics summary of compilation statistics' })
  async getMetricsSummary() {
    return this.clsiService.getMetricsSummary();
  }

  @Post('clsi/admin/clean-scratch')
  @ApiOperation({ summary: 'Trigger LRU garbage collection and disk quota enforcement' })
  async cleanScratch() {
    const staleStats = await this.clsiService.cleanStaleScratch();
    const quotaStats = await this.clsiService.enforceScratchQuota();
    return { staleStats, quotaStats };
  }
}
