import { Permission } from '../enums/permissions.enum';
import { ProjectRole } from '../enums/project-role.enum';
import { WorkspaceRole } from '../enums/workspace-role.enum';

export const WORKSPACE_ROLE_PERMISSIONS: Record<WorkspaceRole, Permission[]> = {
  [WorkspaceRole.OWNER]: Object.values(Permission),
  [WorkspaceRole.ADMIN]: Object.values(Permission),
  [WorkspaceRole.MEMBER]: [
    Permission.WORKSPACE_READ,
    Permission.WORKSPACE_VIEW,
    Permission.PROJECT_READ,
    Permission.PROJECT_VIEW,
  ],
  [WorkspaceRole.VIEWER]: [
    Permission.WORKSPACE_READ,
    Permission.WORKSPACE_VIEW,
    Permission.PROJECT_READ,
    Permission.PROJECT_VIEW,
  ],
};

export const PROJECT_ROLE_PERMISSIONS: Record<ProjectRole, Permission[]> = {
  [ProjectRole.OWNER]: [
    Permission.PROJECT_READ,
    Permission.PROJECT_VIEW,
    Permission.PROJECT_EDIT,
    Permission.PROJECT_UPDATE,
    Permission.PROJECT_DELETE,
    Permission.PROJECT_MANAGE_MEMBERS,
    Permission.COMMENT_CREATE,
    Permission.COMMENT_DELETE,
    Permission.DOCUMENT_VIEW,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_EDIT,
    Permission.DOCUMENT_DELETE,
    Permission.DOCUMENT_COMMENT,
    Permission.LIBRARY_VIEW,
    Permission.LIBRARY_UPLOAD,
    Permission.LIBRARY_DELETE,
    Permission.LIBRARY_EXPORT,
    Permission.TASK_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_EDIT,
    Permission.TASK_DELETE,
    Permission.TASK_ASSIGN,
    Permission.AI_EXECUTE,
    Permission.AI_MANAGE_PROMPTS,
  ],
  [ProjectRole.ADMIN]: [
    Permission.PROJECT_READ,
    Permission.PROJECT_VIEW,
    Permission.PROJECT_EDIT,
    Permission.PROJECT_UPDATE,
    Permission.PROJECT_MANAGE_MEMBERS,
    Permission.COMMENT_CREATE,
    Permission.COMMENT_DELETE,
    Permission.DOCUMENT_VIEW,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_EDIT,
    Permission.DOCUMENT_DELETE,
    Permission.DOCUMENT_COMMENT,
    Permission.LIBRARY_VIEW,
    Permission.LIBRARY_UPLOAD,
    Permission.LIBRARY_DELETE,
    Permission.LIBRARY_EXPORT,
    Permission.TASK_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_EDIT,
    Permission.TASK_DELETE,
    Permission.TASK_ASSIGN,
    Permission.AI_EXECUTE,
    Permission.AI_MANAGE_PROMPTS,
  ],
  [ProjectRole.CONTRIBUTOR]: [
    Permission.PROJECT_READ,
    Permission.PROJECT_VIEW,
    Permission.COMMENT_CREATE,
    Permission.DOCUMENT_VIEW,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_EDIT,
    Permission.DOCUMENT_COMMENT,
    Permission.LIBRARY_VIEW,
    Permission.LIBRARY_UPLOAD,
    Permission.TASK_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_EDIT,
    Permission.TASK_ASSIGN,
    Permission.AI_EXECUTE,
  ],
  [ProjectRole.COMMENTER]: [
    // GVHD / Reviewer: view everything, comment, export citations — cannot create tasks or upload
    Permission.PROJECT_READ,
    Permission.PROJECT_VIEW,
    Permission.COMMENT_CREATE,
    Permission.DOCUMENT_VIEW,
    Permission.DOCUMENT_COMMENT,
    Permission.LIBRARY_VIEW,
    Permission.LIBRARY_EXPORT,
    Permission.TASK_VIEW,
  ],
  [ProjectRole.VIEWER]: [
    // Hội đồng: strictly read-only, no writes at all
    Permission.PROJECT_READ,
    Permission.PROJECT_VIEW,
    Permission.DOCUMENT_VIEW,
    Permission.LIBRARY_VIEW,
    Permission.LIBRARY_EXPORT,
    Permission.TASK_VIEW,
  ],
};
