import { Permission } from '../enums/permissions.enum';
import { WorkspaceRole } from '../enums/workspace-role.enum';
import { ProjectRole } from '../enums/project-role.enum';

export const WORKSPACE_ROLE_PERMISSIONS: Record<WorkspaceRole, Permission[]> = {
  [WorkspaceRole.OWNER]: [
    Permission.WORKSPACE_VIEW,
    Permission.WORKSPACE_EDIT,
    Permission.WORKSPACE_DELETE,
    Permission.WORKSPACE_MANAGE_MEMBERS,
    Permission.WORKSPACE_MANAGE_ROLES,
    Permission.PROJECT_VIEW,
    Permission.PROJECT_CREATE,
    Permission.PROJECT_EDIT,
    Permission.PROJECT_DELETE,
    Permission.PROJECT_MANAGE_MEMBERS,
    Permission.DOCUMENT_VIEW,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_EDIT,
    Permission.DOCUMENT_DELETE,
    Permission.DOCUMENT_COMMENT,
    Permission.LIBRARY_VIEW,
    Permission.LIBRARY_UPLOAD,
    Permission.LIBRARY_DELETE,
    Permission.LIBRARY_EXPORT,
    Permission.TASK_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_EDIT,
    Permission.TASK_DELETE,
    Permission.TASK_ASSIGN,
    Permission.AI_EXECUTE,
    Permission.AI_MANAGE_PROMPTS,
  ],
  [WorkspaceRole.ADMIN]: [
    Permission.WORKSPACE_VIEW,
    Permission.WORKSPACE_EDIT,
    Permission.WORKSPACE_MANAGE_MEMBERS,
    Permission.PROJECT_VIEW,
    Permission.PROJECT_CREATE,
    Permission.PROJECT_EDIT,
    Permission.PROJECT_DELETE,
    Permission.PROJECT_MANAGE_MEMBERS,
    Permission.DOCUMENT_VIEW,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_EDIT,
    Permission.DOCUMENT_DELETE,
    Permission.DOCUMENT_COMMENT,
    Permission.LIBRARY_VIEW,
    Permission.LIBRARY_UPLOAD,
    Permission.LIBRARY_DELETE,
    Permission.LIBRARY_EXPORT,
    Permission.TASK_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_EDIT,
    Permission.TASK_DELETE,
    Permission.TASK_ASSIGN,
    Permission.AI_EXECUTE,
    Permission.AI_MANAGE_PROMPTS,
  ],
  [WorkspaceRole.MEMBER]: [
    Permission.WORKSPACE_VIEW,
    Permission.PROJECT_VIEW,
    Permission.PROJECT_CREATE,
    Permission.DOCUMENT_VIEW,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_EDIT,
    Permission.DOCUMENT_COMMENT,
    Permission.LIBRARY_VIEW,
    Permission.LIBRARY_UPLOAD,
    Permission.LIBRARY_EXPORT,
    Permission.TASK_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_EDIT,
    Permission.TASK_ASSIGN,
    Permission.AI_EXECUTE,
  ],
  [WorkspaceRole.VIEWER]: [
    Permission.WORKSPACE_VIEW,
    Permission.PROJECT_VIEW,
    Permission.DOCUMENT_VIEW,
    Permission.DOCUMENT_COMMENT,
    Permission.LIBRARY_VIEW,
    Permission.LIBRARY_EXPORT,
    Permission.TASK_VIEW,
  ],
};

export const PROJECT_ROLE_PERMISSIONS: Record<ProjectRole, Permission[]> = {
  [ProjectRole.ADMIN]: [
    Permission.PROJECT_VIEW,
    Permission.PROJECT_EDIT,
    Permission.PROJECT_DELETE,
    Permission.PROJECT_MANAGE_MEMBERS,
    Permission.DOCUMENT_VIEW,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_EDIT,
    Permission.DOCUMENT_DELETE,
    Permission.DOCUMENT_COMMENT,
    Permission.LIBRARY_VIEW,
    Permission.LIBRARY_UPLOAD,
    Permission.LIBRARY_DELETE,
    Permission.LIBRARY_EXPORT,
    Permission.TASK_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_EDIT,
    Permission.TASK_DELETE,
    Permission.TASK_ASSIGN,
    Permission.AI_EXECUTE,
    Permission.AI_MANAGE_PROMPTS,
  ],
  [ProjectRole.CONTRIBUTOR]: [
    Permission.PROJECT_VIEW,
    Permission.DOCUMENT_VIEW,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_EDIT,
    Permission.DOCUMENT_COMMENT,
    Permission.LIBRARY_VIEW,
    Permission.LIBRARY_UPLOAD,
    Permission.TASK_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_EDIT,
    Permission.AI_EXECUTE,
  ],
  [ProjectRole.COMMENTER]: [
    Permission.PROJECT_VIEW,
    Permission.DOCUMENT_VIEW,
    Permission.DOCUMENT_COMMENT,
    Permission.LIBRARY_VIEW,
    Permission.LIBRARY_EXPORT,
    Permission.TASK_VIEW,
  ],
  [ProjectRole.VIEWER]: [
    Permission.PROJECT_VIEW,
    Permission.DOCUMENT_VIEW,
    Permission.DOCUMENT_COMMENT,
    Permission.LIBRARY_VIEW,
    Permission.LIBRARY_EXPORT,
    Permission.TASK_VIEW,
  ],
};
